---

- name: begin custom sampledata task
  debug:
    msg: '##### CUSTOM SAMPLEDATA #####'

- name: does the sampledata directory exist?
  stat:
    path: "{{ dataverse.custom_sampledata.custom_sampledir }}"
  register: sampledir_exists

- ansible.builtin.import_tasks: dataverse-sampledata-examples.yml
  when: sampledir_exists.stat.exists == false

- ansible.builtin.import_tasks: dataverse-apitoken.yml
    
- name: publish root dataverse
  shell: 'curl -s --insecure -u {{ api_token }}: -X POST -H "In-Progress: false" --data-binary @- http://localhost:8080/dvn/api/data-deposit/v1.1/swordv2/edit/dataverse/root'
  ignore_errors: yes

- name: get dv-root.json
  get_url:
    url: '{{ dataverse_raw_repo }}/develop/scripts/api/data/dv-root.json'
    dest: "{{ playbook_dir }}/"

- name: grant authusers add-on-root
  uri:
    url: 'http://localhost:8080/api/dataverses/root/assignments?key={{ api_token }}'
    method: POST
    headers:
      Content-Type: "application/json"
    body: '{"assignee": ":authenticated-users","role": "fullContributor"}'
    body_format: json

# users next because in phil's scripts the users create datasets
- name: set user management quesadilla
  uri:
    url: 'http://localhost:8080/api/admin/settings/BuiltinUsers.KEY'
    method: PUT
    body: '{{ dataverse.usermgmtkey }}'

# in theory this should find create-users.sh and any other script
- name: find scripts in user sampledata dir
  find:
    path: "{{ dataverse.custom_sampledata.custom_sampleusers }}"
    file_type: "file"
    pattern: '*.sh'
  register: sampleuserscript_list

# but the above find command fails outside of vagrant(?!?)
# so let's hard-code create-users.sh for now
- name: run scripts in sampleuser dir
  shell: '{{ dataverse.custom_sampledata.custom_sampleusers }}/create-users.sh {{ dataverse.custom_sampledata.custom_sampleusers }}'
  args:
    chdir: '{{ dataverse.custom_sampledata.custom_sampleusers }}'
  
- name: read sampledataverse file list
  find:
    path: "{{ dataverse.custom_sampledata.custom_sampledataverses }}"
    file_type: "file"
  register: sampledataverses_list

- name: import sample dataverses
  uri:
    url: 'http://localhost:8080/api/dataverses/1?key={{ api_token }}'
    method: POST
    headers:
      Content-Type: "application/json"
    src: '{{ item.path }}'
    body_format: json
    status_code: 201
  with_items: "{{ sampledataverses_list.files }}"

- name: read sampledatasets script list
  find:
    path: "{{ dataverse.custom_sampledata.custom_sampledatasets }}"
    file_type: "file"
    pattern: '*.sh'
  register: sampledatasetscripts_list

- name: run sampledatasets scripts
  shell: '{{ item.path }} {{ api_token }} {{ dataverse.custom_sampledata.custom_sampledatasets }}'
  args:
    chdir: '{{ dataverse.custom_sampledata.custom_sampledatasets }}'
  with_items: '{{ sampledatasetscripts_list.files }}'

- name: read sampledatafile script list
  find:
    path: "{{ dataverse.custom_sampledata.custom_samplefiles }}"
    file_type: "file"
    pattern: '*.sh'
  register: sampledatafilescripts_list

- name: run sampledatafile scripts
  shell: '{{ item.path }} {{ api_token }} {{ dataverse.custom_sampledata.custom_samplefiles }}'
  args:
    chdir: '{{ dataverse.custom_sampledata.custom_samplefiles }}'
  with_items: '{{ sampledatafilescripts_list.files }}'
