---

# for hostname and siteUrl
- ansible.builtin.import_tasks: dataverse-fqdn.yml

- name: install grafana
  debug:
    msg: '##### GRAFANA #####'

- name: install grafana repo
  copy:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
    owner: root
    group: root
    mode: '0644'

- name: place grafana repo key
  get_url:
    url: https://packages.grafana.com/gpg.key
    dest: /etc/pki/rpm-gpg/grafana.key
    mode: '0644'

- name: install grafana
  yum:
    name: grafana
    state: latest

- name: set admin password
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;admin_password'
    line: 'admin_password = {{ grafana.grafana_password }}'

- name: enable anonymous access
  lineinfile:
    path: /etc/grafana/grafana.ini
    insertafter: '^# enable anonymous access'
    line: 'enabled = true'

- name: bind to localhost
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^http_addr'
    line: 'http_addr = 127.0.0.1'

- name: set root_url
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;root_url'
    line: 'root_url = http://{{ public_fqdn }}/grafana'

- name: serve grafana from subdir
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: 'serve_from_sub_path '
    line: 'serve_from_sub_path = true'

#- name: create grafana datasource
#  grafana_datasource:
#    access: direct
#    name: "prometheus"
#    grafana_url: '{{ siteUrl }}/grafana'
#    grafana_user: '{{ grafana.grafana_user }}'
#    grafana_password: '{{ grafana.grafana_password }}'
#    ds_type: "prometheus"
#    url: '{{ siteUrl }}/prometheus'
#    database: "prometheus"
#    is_default: "yes"
#    state: present

#- name: import grafana dashboard
#  grafana_dashboard:
#    grafana_url: '{{ siteUrl }}/grafana'
#    grafana_user: '{{ grafana.grafana_user }}'
#    grafana_password: '{{ grafana.grafana_password }}'
#    path: /etc/grafana/grafana-dashboard.json
#    overwrite: yes
#    state: present

- name: remove grafana sample templates
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/grafana/provisioning/dashboards/sample.yaml
    - /etc/grafana/provisioning/datasources/sample.yaml

- name: place grafana datasource template
  template:
    src: dataverse-datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/dataverse-datasource.yml
    owner: root
    group: root
    mode: '0644'

- name: place grafana dashboard yml
  copy:
    src: dataverse-dashboards.yml
    dest: /etc/grafana/provisioning/dashboards/dataverse-dashboards.yml

- name: ensure grafana dashboard dir exists
  file:
    path: /etc/grafana/dashboards
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: place grafana dashboard template
  copy:
    src: grafana-dashboard.json
    dest: /etc/grafana/dashboards/grafana-dashboard.json
    owner: root
    group: root
    mode: '0644'

- name: set dataverse5 as default home dashboard
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;default_home_dashboard_path'
    line: 'default_home_dashboard_path = /etc/grafana/dashboards/grafana-dashboard.json'

- name: reload systemd, enable grafana, start
  systemd:
    name: grafana-server
    enabled: yes
    daemon_reload: yes
    state: started
