---

- name: we need yum-utils
  yum:
    name: yum-utils
    state: latest

- name: to install the docker-ce repo
  shell: 'yum-config-manager --add-repo {{ localstack.docker.repo }}'

- name: install docker-ce
  yum:
    name: ['docker-ce','docker-ce-cli','containerd.io','docker-compose','python-docker-py']

- name: ensure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: configure cidr range
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  when: localstack.docker.cidr is undefined

- name: add ansible_user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: reload systemd, enable docker, start
  systemd:
    name: docker
    enabled: yes
    daemon_reload: yes
    state: started

# so we can run localstack task stand-alone
- ansible.builtin.import_tasks: dataverse-fqdn.yml

- name: is hostname_external set
  set_fact:
    hostname_external: '{{ public_fqdn }}'
  when: localstack.hostname_external is undefined

- name: place docker-compose.yml template
  template:
    src: localstack-compose.yml.j2
    dest: '{{ ansible_env.HOME }}/localstack-compose.yml'

- name: start s3-test container
  shell: 'docker-compose -f localstack-compose.yml up -d'
  args:
    chdir: '{{ ansible_env.HOME }}'
